### PR TITLE
[WIP] API class refactor

### PR DESCRIPTION
**Pull request by FurkanKambay**
- [x] Clean up API class
- [x] Make API functions async
- [x] Clean up duplicate properties in models
- [x] Rename properties in models to PascalCase
- [ ] Apply Json attributes to model properties
- [ ] Improve and rename Api class (CodClient?)

Also, I think the API class should be renamed to something like "CodApi" to clearly show where it's from. (I mean, otherwise the user might need to prefix the namespace like `CODBO4.Api` which is not awesome)

### CODE REVIEW

**Comment by ohhsodead** [comment]
That's amazing, thanks for your work. Any chance of cleaning the solution, including classes would be much appreciated. Supporting Json attributes will be great too, many thanks. This project is something I need to pick up soon, so apologies for the messy code.

**Comment by FurkanKambay** [comment]
No worries! I'll do those when I can.

**Comment by FurkanKambay** [comment]
I'm gonna re-review the latest commit tomorrow (probably) and then I'll do the naming stuff.

**Comment by FurkanKambay** [comment]
Just realized there is also a `multiplayerExtra` but there was no example for that. That class should be added. And there are some stuff like `weaponData` which should also have its own class.

**Comment by ohhsodead** [comment]
Thank you for noticing, I had no idea about that. Seems like this needs some long awaited tests before the next update as it's mostly unfinished. I'll be sure to add the following files very soon.  Thank you very much for your help!

**Pull request merged**
